### ISSUE TITLE
ERROR: Service 'connect' has a link to service 'mysql' which is undefined.

### ISSUE THREAD

**Issue by mbiombani** [izhangzhihao/Real-time-Data-Warehouse#1]
i have error, docker-compose up

ERROR: Service 'connect' has a link to service 'mysql' which is undefined.

**Comment by izhangzhihao** [comment]
Fixed

**Comment by mbiombani** [comment]
thanks !

I have a another error

Step 5/6 : COPY jars/* /opt/flink/lib/
COPY failed: no source files were specified
ERROR: Service 'flink-base-img' failed to build : Build failed

**Comment by izhangzhihao** [comment]
If you need additional jar files(sometimes, HUDI support need you build your own jar file), put them into `jar` folder, otherwise, you can remove this step from `Dockerfile`
