### ISSUE TITLE
Error response from daemon: pull access denied for rtdw/flink-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by penghuachong** [izhangzhihao/Real-time-Data-Warehouse#2]
你好，我直接clone代码下来启动会报这个错误，Error response from daemon: pull access denied for rtdw/flink-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by izhangzhihao** [comment]
需要先运行 docker compose build

**Comment by penghuachong** [comment]
build的时候提示 rtdw/flink-base  不存在或者没权限，然后我search一下也没看到有这个rtdw/flink-base。可否指导一下？本人docker接触不久哈哈，谢谢。
